# Auto-generated dicts from SPECIAL CMD section
# Generated by convert_cmds_to_dicts.py

CMD_TOTAL = {
    "MSG_SPEC_HELLO": "msg_spec_hello",  # line 22
    "SYS_SPEC_GOING_TO_REBOOT": "msg_spec_going_to_reboot",  # line 24
    "MSG_GET_SW_VERSION": "msg_get_sw_version",  # line 32
    "LE_GET_SW_VERSION": "le_get_sw_version",  # line 33
    "DEMO_GET_SW_VERSION": "demo_get_sw_version",  # line 34
    "SYS_GET_SW_VERSION": "sys_get_sw_version",  # line 35
    "SYS_GET_WIFI_UAP0_SSID": "sys_get_wifi_uap0_ssid",  # line 38
    "SYS_GET_WIFI_UAP0_PWD": "sys_get_wifi_uap0_pwd",  # line 39
    "SYS_GET_WIFI_UAP0_SSID_PWD": "sys_get_wifi_uap0_ssid_pwd",  # line 40
    "SYS_GET_WIFI_UAP0_HW_MODE": "sys_get_wifi_uap0_hw_mode",  # line 41
    "LE_GET_BRIGHTNESS": "le_get_luminance",  # line 44
    "LE_GET_CURRENT": "le_get_current",  # line 45
    "LE_GET_TEMPERATURE": "le_get_temperature",  # line 46
    "LE_GET_MIRROR": "le_get_mirror",  # line 47
    "LE_GET_FLIP": "le_get_flip",  # line 48
    "LE_GET_OFFSET": "le_get_offset",  # line 49
    "DEMO_SET_PLAY_MEDIA": "demo_set_play_media",  # line 56
    "SYS_SET_WIFI_SSID": "sys_set_wifi_ssid",  # line 57
    "LE_SET_BRIGHTNESS": "le_set_brightness",  # line 60
    "LE_SET_CURRENT": "le_set_current",  # line 61
    "LE_SET_TEMPERATURE": "le_set_temperature",  # line 62
    "LE_SET_MIRROR": "le_set_mirror",  # line 63
    "LE_SET_FLIP": "le_set_flip",  # line 64
    "LE_SET_OFFSET": "le_set_offset",  # line 65
    "DEMO_SET_TEST": "demo_set_test",  # line 68
    "SYS_SET_TEST": "sys_set_test",  # line 69
    "LE_SET_TEST": "le_set_test",  # line 70
    "SYS_SET_WIFI_UAP0_SSID": "sys_set_wifi_uap0_ssid",  # line 73
    "SYS_SET_WIFI_UAP0_PWD": "sys_set_wifi_uap0_pwd",  # line 74
    "SYS_SET_WIFI_UAP0_SSID_PWD": "sys_set_wifi_uap0_ssid_pwd",  # line 75
    "SYS_SET_WIFI_UAP0_HW_MODE": "sys_s/et_wifi_uap0_hw_mode",  # line 76
}

# Section: SPEC_CMD_SYS_Reboot
SPEC_CMD_SYS_Reboot = {
    "SYS_SPEC_GOING_TO_REBOOT": "msg_spec_going_to_reboot",  # line 24
}

# Section: GET_CMD_VERSION
GET_CMD_VERSION = {
    "MSG_GET_SW_VERSION": "msg_get_sw_version",  # line 32
    "LE_GET_SW_VERSION": "le_get_sw_version",  # line 33
    "DEMO_GET_SW_VERSION": "demo_get_sw_version",  # line 34
    "SYS_GET_SW_VERSION": "sys_get_sw_version",  # line 35
}

# Section: GET_CMD_SYS_Wifi
GET_CMD_SYS_Wifi = {
    "SYS_GET_WIFI_UAP0_SSID": "sys_get_wifi_uap0_ssid",  # line 38
    "SYS_GET_WIFI_UAP0_PWD": "sys_get_wifi_uap0_pwd",  # line 39
    "SYS_GET_WIFI_UAP0_SSID_PWD": "sys_get_wifi_uap0_ssid_pwd",  # line 40
    "SYS_GET_WIFI_UAP0_HW_MODE": "sys_get_wifi_uap0_hw_mode",  # line 41
}

# Section: GET_CMD_LE
GET_CMD_LE = {
    "LE_GET_BRIGHTNESS": "le_get_luminance",  # line 44
    "LE_GET_CURRENT": "le_get_current",  # line 45
    "LE_GET_TEMPERATURE": "le_get_temperature",  # line 46
    "LE_GET_MIRROR": "le_get_mirror",  # line 47
    "LE_GET_FLIP": "le_get_flip",  # line 48
    "LE_GET_OFFSET": "le_get_offset",  # line 49
}

# Section: SET_CMD
SET_CMD = {
    "DEMO_SET_PLAY_MEDIA": "demo_set_play_media",  # line 56
    "SYS_SET_WIFI_SSID": "sys_set_wifi_ssid",  # line 57
}

# Section: SET_CMD_LE
SET_CMD_LE = {
    "LE_SET_BRIGHTNESS": "le_set_brightness",  # line 60
    "LE_SET_CURRENT": "le_set_current",  # line 61
    "LE_SET_TEMPERATURE": "le_set_temperature",  # line 62
    "LE_SET_MIRROR": "le_set_mirror",  # line 63
    "LE_SET_FLIP": "le_set_flip",  # line 64
    "LE_SET_OFFSET": "le_set_offset",  # line 65
}

# Section: SET_CMD TEST
SET_CMD_TEST = {
    "DEMO_SET_TEST": "demo_set_test",  # line 68
    "SYS_SET_TEST": "sys_set_test",  # line 69
    "LE_SET_TEST": "le_set_test",  # line 70
}

# Section: SET_CMD_SYS_Wifi
SET_CMD_SYS_Wifi = {
    "SYS_SET_WIFI_UAP0_SSID": "sys_set_wifi_uap0_ssid",  # line 73
    "SYS_SET_WIFI_UAP0_PWD": "sys_set_wifi_uap0_pwd",  # line 74
    "SYS_SET_WIFI_UAP0_SSID_PWD": "sys_set_wifi_uap0_ssid_pwd",  # line 75
    "SYS_SET_WIFI_UAP0_HW_MODE": "sys_s/et_wifi_uap0_hw_mode",  # line 76
}
