# Auto-generated dicts from SPECIAL CMD section
# Generated by convert_cmds_to_dicts.py

CMD_TOTAL = {
    "MSG_SPEC_HELLO": "msg_spec_hello",  # line 19
    "SYS_SPEC_GOING_TO_REBOOT": "msg_spec_going_to_reboot",  # line 21
    "MSG_GET_SW_VERSION": "msg_get_sw_version",  # line 24
    "LE_GET_SW_VERSION": "le_get_sw_version",  # line 25
    "DEMO_GET_SW_VERSION": "demo_get_sw_version",  # line 26
    "SYS_GET_SW_VERSION": "sys_get_sw_version",  # line 27
    "SYS_GET_WIFI_UAP0_SSID": "sys_get_wifi_uap0_ssid",  # line 30
    "SYS_GET_WIFI_UAP0_PWD": "sys_get_wifi_uap0_pwd",  # line 31
    "SYS_GET_WIFI_UAP0_SSID_PWD": "sys_get_wifi_uap0_ssid_pwd",  # line 32
    "SYS_GET_WIFI_UAP0_HW_MODE": "sys_get_wifi_uap0_hw_mode",  # line 33
    "DEMO_SET_PLAY_MEDIA": "demo_set_play_media",  # line 37
    "SYS_SET_WIFI_SSID": "sys_set_wifi_ssid",  # line 38
    "LE_SET_BRIGHTNESS": "le_set_brightness",  # line 39
    "DEMO_SET_TEST": "demo_set_test",  # line 42
    "SYS_SET_TEST": "sys_set_test",  # line 43
    "LE_SET_TEST": "le_set_test",  # line 44
    "SYS_SET_WIFI_UAP0_SSID": "sys_set_wifi_uap0_ssid",  # line 47
    "SYS_SET_WIFI_UAP0_PWD": "sys_set_wifi_uap0_pwd",  # line 48
    "SYS_SET_WIFI_UAP0_SSID_PWD": "sys_set_wifi_uap0_ssid_pwd",  # line 49
    "SYS_SET_WIFI_UAP0_HW_MODE": "sys_s/et_wifi_uap0_hw_mode",  # line 50
}

# Section: SPEC_CMD_SYS_Reboot
SPEC_CMD_SYS_Reboot = {
    "SYS_SPEC_GOING_TO_REBOOT": "msg_spec_going_to_reboot",  # line 21
}

# Section: GET_CMD_VERSION
GET_CMD_VERSION = {
    "MSG_GET_SW_VERSION": "msg_get_sw_version",  # line 24
    "LE_GET_SW_VERSION": "le_get_sw_version",  # line 25
    "DEMO_GET_SW_VERSION": "demo_get_sw_version",  # line 26
    "SYS_GET_SW_VERSION": "sys_get_sw_version",  # line 27
}

# Section: GET_CMD_SYS_Wifi
GET_CMD_SYS_Wifi = {
    "SYS_GET_WIFI_UAP0_SSID": "sys_get_wifi_uap0_ssid",  # line 30
    "SYS_GET_WIFI_UAP0_PWD": "sys_get_wifi_uap0_pwd",  # line 31
    "SYS_GET_WIFI_UAP0_SSID_PWD": "sys_get_wifi_uap0_ssid_pwd",  # line 32
    "SYS_GET_WIFI_UAP0_HW_MODE": "sys_get_wifi_uap0_hw_mode",  # line 33
}

# Section: SET_CMD
SET_CMD = {
    "DEMO_SET_PLAY_MEDIA": "demo_set_play_media",  # line 37
    "SYS_SET_WIFI_SSID": "sys_set_wifi_ssid",  # line 38
    "LE_SET_BRIGHTNESS": "le_set_brightness",  # line 39
}

# Section: SET_CMD TEST
SET_CMD_TEST = {
    "DEMO_SET_TEST": "demo_set_test",  # line 42
    "SYS_SET_TEST": "sys_set_test",  # line 43
    "LE_SET_TEST": "le_set_test",  # line 44
}

# Section: SET_CMD_SYS_Wifi
SET_CMD_SYS_Wifi = {
    "SYS_SET_WIFI_UAP0_SSID": "sys_set_wifi_uap0_ssid",  # line 47
    "SYS_SET_WIFI_UAP0_PWD": "sys_set_wifi_uap0_pwd",  # line 48
    "SYS_SET_WIFI_UAP0_SSID_PWD": "sys_set_wifi_uap0_ssid_pwd",  # line 49
    "SYS_SET_WIFI_UAP0_HW_MODE": "sys_s/et_wifi_uap0_hw_mode",  # line 50
}
